language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          packages:
          - cmake
          update: true

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
          update: true
      env:
        - CC=gcc-7
        - CXX=g++-7

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-8
          update: true
      env:
        - CC=gcc-8
        - CXX=g++-8

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - bash .travis/build.sh

after_success:
- bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
